### ISSUE TITLE
Doesn't support custom padding ?

### ISSUE THREAD

**Issue by suclogger** [crypto-browserify/publicEncrypt#11]
As [crypto api](https://nodejs.org/api/crypto.html) indicates : 
>crypto.publicEncrypt(public_key, buffer)#

>Encrypts buffer with public_key.

>public_key can be an object or a string. If public_key is a string, it is treated as the key with no passphrase and will use RSA_PKCS1_OAEP_PADDING. If public_key is an object, it is interpreted as a hash object with the keys:

>key : <String> - PEM encoded public key
>passphrase : <String> - Optional passphrase for the private key
>padding : An optional padding value, one of the following:
>crypto.constants.RSA_NO_PADDING
>crypto.constants.RSA_PKCS1_PADDING
>crypto.constants.RSA_PKCS1_OAEP_PADDING

There are several padding options.
But it seems crypto-browserify doesn't support this?

**Comment by calvinmetcalf** [comment]
We support it, if you have an issue with the padding not working please open an issue with that and we can try to troubleshoot
