### ISSUE TITLE
Decryption error when running in the browser

### ISSUE THREAD

**Issue by lowe0292** [crypto-browserify/publicEncrypt#12]
I'm able to use this module to successfully decrypt a message from my terminal, but when I run the code in the browser (9.0.4), I get `Error: decryption error` which I traced back to https://github.com/crypto-browserify/publicEncrypt/blob/master/privateDecrypt.js#L51

Any idea why this works in node but not in the browser, or how to fix it?

**Comment by calvinmetcalf** [comment]
I'm at a conference so I should be able to look into this when I get back
next week, but in node we actually use the node crypto stuff but in the
browser we are using a pure js version which may have a bug

**Comment by dcousens** [comment]
@lowe0292 if you can provide the parameters for that error, that'd be great.
