### ISSUE TITLE
OAEP encryption using SHA1?

### ISSUE THREAD

**Issue by core433** [crypto-browserify/publicEncrypt#13]
Public Encrypt is using sha1 for the hash function, is that secure?  It sounds like sha1 is being deprecated because it's been theoretically crackable since 2005.  Is this the same hash function that node crypto is using / are they not on sha2 / sha256?

**Comment by calvinmetcalf** [comment]
This is what node uses and a very quick read through [the spec](https://tools.ietf.org/html/rfc2437) looks like it's called for explicitly.

More generally hashes can fail in multiple ways, the way SHA1 has been broken is that researchers have been able to generate 2 different things that hash the same, OAEP unlike say, signatures, doesn't rely on this aspect of the hash function, but instead relies on the fact that given a hash, you shouldn't be able to figure out the message that hashes to it and that is less broken.  

That being said from my understanding, RSA is not where the energy is going and and you should probably be using elliptical curve based stuff if you need to send secret data.
