### ISSUE TITLE
Link to blog

### ISSUE THREAD

**Issue by dcousens** [crypto-browserify/publicEncrypt#17]
@calvinmetcalf the number of packages surrounding this functionality is still insanely substantial.

You should link to your blog which explains the process you took, as it is quite educational for the topics involved.

http://calvinmetcalf.com/post/104082905653/porting-nodejs-crypto-to-the-browser-part-1-all
http://calvinmetcalf.com/post/105264858108/porting-nodejs-crypto-to-the-browser-part-2
http://calvinmetcalf.com/post/109301244759/porting-nodejs-crypto-to-the-browser-part-3

**Comment by calvinmetcalf** [comment]
added as part of #16

**Comment by dcousens** [comment]
LGTM
