### ISSUE TITLE
Twistlock security scan shows that private keys are stored in the container

### ISSUE THREAD

**Issue by sanknmFinicity** [crypto-browserify/publicEncrypt#23]
Twistlock vulnerability scans raise a compliance alarm on images containing public-encrypt package

Private keys stored in image:
..x.../node_modules/public-encrypt/test/1024.priv,
..x.../node_modules/public-encrypt/test/ec.pass.priv,
..x.../node_modules/public-encrypt/test/ec.priv,
..x.../node_modules/public-encrypt/test/pass.1024.priv,
..x.../node_modules/public-encrypt/test/rsa.1024.priv,
..x.../node_modules/public-encrypt/test/rsa.2028.priv,
..x.../node_modules/public-encrypt/test/rsa.pass.priv,
..x.../node_modules/public-encrypt/test/test_key.pem,
..x.../node_modules/public-encrypt/test/test_rsa_privkey.pem,
..x.../node_modules/public-encrypt/test/test_rsa_privkey_encrypted.pem, 

Expected outcome
Successful Twistlock scan completion without errors.

Actual outcome
Twistlock raises a compliance issue because key file are included.

Suggested fix
Do not include private keys in the node module.

**Comment by calvinmetcalf** [comment]
yes, this is a library that deals with public keys and includes ones that we can test against, this is a false positive from twistlock
